# Generated by Django 4.1.5 on 2023-12-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="X2AXRF4QA32KX324MEDHJPUX7Q7GWDPJ", max_length=100
            ),
        ),
    ]
