# Generated by Django 4.1.5 on 2023-12-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="4MVOZBVO25H2HK7J7AXWL5Q3VAUM45YT", max_length=100
            ),
        ),
    ]
