# Generated by Django 4.1.5 on 2023-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_2fa_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="53BHUSQHDAY2K5RPFLMQSFO6EZFDVWI3", max_length=100
            ),
        ),
    ]
