# Generated by Django 4.1.5 on 2023-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="6KQPBOADV7ANET2YGH3C5O2G73J2QWG3", max_length=100
            ),
        ),
    ]
