# Generated by Django 4.1.5 on 2023-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="CIILDCABWGGQX4T2JOEOHIYQS3SBGOUY", max_length=100
            ),
        ),
    ]
