# Generated by Django 4.1.5 on 2023-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="QZYETWIDJWBPZN4OJTUD3ZQFCOZD4YFD", max_length=100
            ),
        ),
    ]
