# Generated by Django 4.1.5 on 2023-12-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                default="K6EBR5YEZZTFTNUP5LYN35XF2ZTIZLH7", max_length=100
            ),
        ),
    ]
