# Generated by Django 4.1.5 on 2023-12-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_totp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(default="dummy-secret", max_length=100),
        ),
    ]
